# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'RedditPicsBrowser-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RedditPicsBrowser-iOS
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ProgressHUD'
  pod 'ReachabilitySwift'

  target 'RedditPicsBrowser-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RedditPicsBrowser-iOSUITests' do
    # Pods for testing
  end

end
